"""Message seen field changed

Revision ID: 7fba1d7683c3
Revises: 2340633ea300
Create Date: 2024-10-20 18:27:51.890536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fba1d7683c3'
down_revision: Union[str, None] = '2340633ea300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'seen',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'seen',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
