"""Message timestamp default value

Revision ID: ecc4097ed7e4
Revises: 8c362bc4426b
Create Date: 2024-10-20 16:58:16.955029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc4097ed7e4'
down_revision: Union[str, None] = '8c362bc4426b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
